# Configuración SSL completa
systemProp.jdk.insecure.ssl.ignoreAllCertIssues=true
systemProp.jdk.tls.client.protocols=TLSv1.2,TLSv1.3
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT

# Configuración de Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true



# 3. Habilita el "Gradle Daemon", un proceso en segundo plano que mantiene la info de tu proyecto en memoria.
org.gradle.daemon=true

# 4. Habilita la "Configuración bajo demanda". En proyectos multi-módulo, configura solo los módulos necesarios.
org.gradle.configureondemand=true