# Configuración SSL completa
systemProp.jdk.insecure.ssl.ignoreAllCertIssues=true
systemProp.jdk.tls.client.protocols=TLSv1.2,TLSv1.3
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT

# Configuración de Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true